name: beliana.sav.web
recipe: drupal9
config:
  php: 8.1
  via: apache
  webroot: web
  drush: 10
services:
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver