name: beliana.web
recipe: drupal8
config:
  php: 7.4
  via: apache
  webroot: web
  xdebug: start
  config:
    php: .lando/php.ini

services:
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver