# Create here the Drupal site you would like
version: '2'
services:
  drupal:
    # Choose your URL and hostname for this Docker Container
    # DO NOT remove the '&hostname'
    hostname: &hostname beliana.docker.amazee.io

    environment:
      WEBROOT: web

      # APC Support is by default enabled, but in some cases it can make issues, change to 0 to disable:
      APC: 1

################################################
### Do not change anything below here, unless you know what you do
      VIRTUAL_HOST: *hostname
    image: amazeeio/drupal:php70-basic
    volumes:
      - .:/var/www/drupal/public_html
    volumes_from:
      - container:amazeeio-ssh-agent
    container_name: *hostname
    network_mode: bridge
    ports:
      - "3306"
    links:
      - solr
  solr:
    image: amazeeio/solr:6
    network_mode: bridge