<?php

/**
 * @file
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function beliana_daily_form_piwik_admin_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::getContainer()->get('config.factory')->getEditable('piwik.settings');

  $form['general']['piwik_access_token'] = [
    '#default_value' => $config->get('access_token'),
    '#description' => t('The API access token to your Piwik instance.'),
    '#maxlength' => 255,
    '#size' => 80,
    '#title' => t('Piwik API token'),
    '#type' => 'textfield',
  ];

  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'beliana_daily_piwik_admin_settings_submit';
    }
  }
}

function beliana_daily_piwik_admin_settings_submit($form, FormStateInterface $form_state) {
  $config = \Drupal::getContainer()->get('config.factory')->getEditable('piwik.settings');
  $config->set('access_token', $form_state->getValue('piwik_access_token'));
  $config->save();
}
