parameters:
  twig.config: # disabling twig debugging and auto reload, plus enabling twig caching
    debug: false
    auto_reload: null
    cache: true
services:
  cache.backend.null:
    class: Drupal\Core\Cache\NullBackendFactory